./installers/spdlog.sh $1 $2
./installers/eigen.sh $1 $2
./installers/valijson.sh $1 $2
./installers/jsoncpp.sh $1 $2
./installers/vulkan_loader.sh $1 $2
./installers/spirv_wrapper.sh $1 $2
./installers/vulkan_tools.sh $1 $2
./installers/vulkan_utilities.sh $1 $2
./installers/vulkan_profiles.sh $1 $2
./installers/vulkan_extension.sh $1 $2
./installers/vulkan_validation.sh $1 $2
./installers/dxc.sh $1 $2
./installers/vma.sh $1 $2